### ISSUE TITLE
Images coffea-dask-almalinux8:v2024.8.3-py3.* Fail for some Microarchs

### ISSUE THREAD

**Issue by rpsimeon34** [CoffeaTeam/af-images#48]
When using the above-named images (ending in either py3.11 or py3.10), Dask workers frequently fail. However, when we request workers with microarch "x86_64-v3" (as opposed to "x86_64-v2"), jobs run successfully.

This issue does not seem to happen with coffea-dask-almalinux8:v2024.5.0-py3.*.

Some details:
We are submitting jobs from a host within a container running the same image as we give to the workers. Workers access images as SIFs in CVMFS. Jobs are submitted at Wisconsin with HTCondor, through `dask-jobqueue`'s `HTCondorCluster`. The only error message we see is a Dask `KilledWorker` exception.

**Comment by oshadura** [comment]
@rpsimeon34 can you try latest tag again, I merged fix https://github.com/CoffeaTeam/af-images/pull/56/commits/a5944aaf98c5e45f2c98c69ad5eeec63d65c0184. All tags that have a fixed where pushed today: https://hub.docker.com/r/coffeateam/coffea-dask-almalinux9/tags

**Comment by oshadura** [comment]
still not fixed, I will try one more iteration, and let you know when it is ready to test

**Comment by ikrommyd** [comment]
The reason this is happening is explained here: https://github.com/CoffeaTeam/af-images/issues/58

Please test again with 2024.11.0. For older images, the solution is to install `awkward` via `pip` in the image.

**Comment by rpsimeon34** [comment]
Thanks, @ikrommyd and @oshadura ! It looks like v2024.11.0 solves this issue (specifically, I tested with coffea-dask-almalinux9:2024.11.0-py3.11)
