### ISSUE TITLE
We should be installing `awkward/awkward-cpp` from `pypi` at the moment to avoid microarch builds

### ISSUE THREAD

**Issue by ikrommyd** [CoffeaTeam/af-images#58]
The conda build of `awkward-cpp` has microarches enabled and creates a build for x86-64-v1 and one for x86-64-v3 at this moment: https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

So during the docker creation procedure `mamba install awkward` (comes from `environment.yml` in this case) detects that the host system building the dockers supports the v3 microarch and installs that. But then, when we try to run the unpacked apptainer on condor workers with older CPUs, since AVX2 isn't supported, we get an `Illegal Instruction` crash.

The solution is to grab `awkward` from pypi for the time being. It isn't enough to specify `awkward` as a `pip` package in `environment.yml` because `conda` will already have installed `awkward` as a `coffea` dependency and then `pip` will say that it already has the newest version installed and ignore it.

The best solution is probably to do `mamba remove awkward awkward-cpp --force` and then `pip install awkward` in the `Dockerfile` after the environment has been created. May also beed good to pin `awkward` in the same way `coffea` does in https://github.com/scikit-hep/coffea/blob/master/pyproject.toml or https://github.com/conda-forge/coffea-feedstock/blob/b7355261e7cb078862daf041108d9cab3a70cf5d/recipe/meta.yaml because the `pip` installation will not care about dependencies. So `pip install awkward>=2.6.7` at the time of writing.

**Comment by oshadura** [comment]
Temporary fix (to be reverted later): https://github.com/CoffeaTeam/af-images/pull/59

**Comment by ikrommyd** [comment]
Closing this as it's fixed in the latest images :)

**Comment by cwseys** [comment]
Hi!  It seems like a more future proof and less fiddly way of solving this problem would be to build the images in virtual machines with a v1 (EL8) or v2 (EL9) microarchecture CPU.  One wouldn't have to lock versions of packages for this reason.

Thanks for all your work!

**Comment by cwseys** [comment]
Oh!  I only saw this bug fix and not the future iterations of the fix!  Thanks!

**Comment by ikrommyd** [comment]
> Oh! I only saw this bug fix and not the future iterations of the fix! Thanks!
> 
> P.S. You've probably already looked into whether CONDA_OVERRIDE_ARCHSPEC also affects the packages installed by conda from the pypi repo. And decided the performance difference of v1 microarch packages compared to v2 in alma9 containers was ignorable. :)

There is probably some small benefit to v3 microarch but negligible but that was only built for conda anyway. The `pypi` version of awkward supports only v1 microarch. This option is the safest regarding the af images at the moment because some still may have old CPUs.
